### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by PixDevTeam** [PixDevTeam/PixOS#1]
When I compile with NASM it gives this Error:
boot.asm:45: error: TIMES value -4688 is negative

Thank You!

**Comment by m44rtn** [comment]
@Tris69  

I hope this fixes it. All you need to know is in the readme.txt file.
good luck and have a nice day!

[fix.zip](https://github.com/Tris69/PixOS/files/176714/fix.zip)

**Comment by PixDevTeam** [comment]
Thanks! I have changed a lot of code since I first commented, but I appreciate the help and you reminded me that I need to update the GitHub code.

**Comment by m44rtn** [comment]
no problem!
I am also working on an OS, but 32-bit in this case.

Maarten, BirdOS

**Comment by m44rtn** [comment]
I don't want to be anoying, but this is done. Right? You can close the issue. Otherwise you have one open which should be closed. :)
